### ISSUE TITLE
Update Release Workflow: Auto Generate Release Notes + Autogenerate Changelog

### ISSUE THREAD

**Issue by ckanitz** [luehrsenheinrich/wp-project-boilerplate#699]
From @vheinrich at VMS:

# Helpful Links
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
https://github.com/luehrsenheinrich/wp-project-boilerplate/releases/tag/v0.0.18

Goal: 
- better changelog in the release

Next Step (when this is done)
- add a changelog.md
- with the changelog.md we get create a automated blogpost at the page
- with the blogpost i can create an automated newsletter to the clients

**Comment by ckanitz** [comment]
### Changelog.md auto generation

There's two workflow marketplace entries to consider:

1. https://github.com/marketplace/actions/auto-generate-changelog
2. https://github.com/marketplace/actions/changelog-ci

Looking at the feature set I'd go for `changelog ci` as I can't see a straight forward way to ignore dependabot bumps with `auto-generate-changelog`

With `Changelog CI` it's also possible to use the generated output for the Github Release Notes as well.

All log generators use regex on PR titles and/or commit titles (depending on config) to determine specific types like "feature", "bug fix" etc. Which makes a guidline on title naming necessary.

So the steps to properly add this to our release workflow we need to:

- setup a [config](https://github.com/marketplace/actions/changelog-ci#configuration)
- define types
- create a guidline for PR/Commit titles
- integrate CI to our existing release workflow

#### Example

Here's how `Changelog CI` could fit in to our current release workflow:

```YML
jobs:
    # ...
     - name: ⚙️ Install Node Packages
        run: npm ci

      # - name: ✍️ Create Changelog
      #   shell: bash
      #   id: changelog
      #   run: |
      #     EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
      #     log=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:'* %s (%h)')
      #     echo "CHANGELOG<<$EOF" >> $GITHUB_ENV
      #     echo "$log" >> $GITHUB_ENV
      #     echo "$EOF" >> $GITHUB_ENV

      - name: Check Status
        run: git status

      - name: 🔼 Bump version
        run: npm version ${{ github.event.inputs.version }} -m 'Tagging %s'

      - name: ⚙️ Get new version
        id: version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: ✍️ Create Changelog
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          # Config including "ignore bump" and
          # maybe type definitions etc.
          config_file: changelog-ci-config.yml
          release_version: ${{ steps.version.outputs.version }}
          github_token: ${{ secrets.GH_ADMIN_TOKEN }}

      - name: Push the version to git
        run: |
            git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}

    # ...
```

** changelog-ci-config.yml **

```YML
changelog_type: 'commit_message' # or 'pull_request'
header_prefix: 'Version:'
commit_changelog: true
comment_changelog: true
exclude_labels:
  - bot
  - dependabot
  - ci
group_config:
  - title: Bug Fixes
    labels:
      - bugfix
  - title: New Features
    labels:
      - feature
  - title: Documentation Updates
    labels:
      - docs
```
